
df = data_preparation.load_data('/Users/cemkoymen/Desktop/hmm_garch/Data/DGS5.csv')
returns = data_preparation.calculate_returns(df)
volatility = data_preparation.calculate_volatility(returns)
labelling = data_preparation.classify_dates(volatility)
z_scored_labels = data_preparation.calculate_rolling_z_scores(labelling)
final_states = data_preparation.calculate_final_score(z_scored_labels)
transition_matrix = data_preparation.compute_transition_matrix(z_scored_labels)
print("Transition Matrix:")
print(transition_matrix)